name: Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_ACCESS_TOKEN }}

    - name: build and push container to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: markoke/local-llm:latest
